spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhangxd1989/spring-boot-cloud
          #          search-paths: repo
          # username:
        # password:

server:
  port: 1201





